export const FETCH_RENTALS_INIT = 'FETCH_RENTALS_INIT';
export const FETCH_RENTALS_SUCCESS = 'FETCH_RENTALS_SUCCESS';
export const FETCH_RENTALS_BY_INIT = 'FETCH_RENTALS_BY_INIT';
export const FETCH_RENTALS_BY_SUCCESS = 'FETCH_RENTALS_BY_SUCCESS';
